version: '3.4'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: "${RESTART}"
    ports:
      - 9000:${PORTAINER_ADMIN_PORT}
      - 8000:${PORTAINER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: